config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'


  resources :dashboard, only: [:index]
  resources :profile, only: [:index]


  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.email              = auth_info.extra.raw_info.email
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user,
                :current_user_name

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user_name
    User.find(current_user.id).screen_name
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    user         = set_user
    @github_user = GitHubUser.new(user)
    @events      = @github_user.events
    @following   = @github_user.following
    @all_events  = @github_user.all_events
    @repos       = @github_user.repos
    @commits     = @github_user.sorted_commits
    @prs         = @github_user.pull_requests
  end

  private

  def set_user
    user = User.find(current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    user         = User.find(current_user.id)
    @github_user = GitHubUser.new(user)
    @profile     = @github_user.profile
    @following   = @github_user.following
    @starred     = @github_user.starred
    @followers   = @github_user.followers
    @repos       = @github_user.repos
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to profile_index_path
    else
      render 404
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logged out successfully'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user/dashboard_helper.rb
module User::DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="mq-panel-wrapper">
  <div class="mq-panel-header">
      <h3>My Recent Activity</h3>
  </div>

  <div class="mq-panel-body">
       <ul class="mq-comment">
                  <div class="mq-comment-body clearfix">
                      <div class="header">
                          <strong class="primary-font"><%= @events.first['type'] %></strong> <small class="pull-right text-muted">
                              <span class="glyphicon glyphicon-time"></span><%= distance_of_time_in_words Time.now, @events.first['created_at'] %></small>
                      </div>
                      <p>
                        <%= @events.first['body'] %>
                      </p>
                  </div>
          </ul>
       <ul class="mq-comment">
                  <div class="mq-comment-body clearfix">
                      <div class="header">
                          <strong class="primary-font"><%= @events[1]['type'] %></strong> <small class="pull-right text-muted">
                              <span class="glyphicon glyphicon-time"></span><%= distance_of_time_in_words Time.now, @events[1]['created_at'] %></small>
                      </div>
                      <p>
                          <%= @events[1]['body'] unless nil %>
                      </p>
                  </div>
          </ul>
       <ul class="mq-comment">
                  <div class="mq-comment-body clearfix">
                      <div class="header">
                          <strong class="primary-font"><%= @events[2]['type'] %></strong> <small class="pull-right text-muted">
                              <span class="glyphicon glyphicon-time"></span><%= distance_of_time_in_words Time.now, @events[2]['created_at'] %></small>
                      </div>
                      <p>
                          <%= @events[2]['body'] unless nil %>
                      </p>
                  </div>
          </ul>
       <ul class="mq-comment">
                  <div class="mq-comment-body clearfix">
                      <div class="header">
                          <strong class="primary-font"><%= @events[3]['type'] %></strong> <small class="pull-right text-muted">
                              <span class="glyphicon glyphicon-time"></span><%= distance_of_time_in_words Time.now, @events[3]['created_at'] %></small>
                      </div>
                      <p>
                          <%= @events[3]['body'] unless nil %>
                      </p>
                  </div>
          </ul>
       <ul class="mq-comment">
                  <div class="mq-comment-body clearfix">
                      <div class="header">
                          <strong class="primary-font"><%= @events[4]['type'] %></strong> <small class="pull-right text-muted">
                              <span class="glyphicon glyphicon-time"></span><%= distance_of_time_in_words Time.now, @events[4]['created_at'] %></small>
                      </div>
                      <p>
                          <%= @events[4]['body'] unless nil %>
                      </p>
                  </div>
          </ul>

  </div>
</div>

<div class="mq-panel-wrapper">
  <div class="mq-panel-header">
      <h3>Following</h3>
  </div>

  <div class="mq-panel-body">
      <div class="mq-friends thumbnail">
              <div class="mq-friend-img text-center">
              <img src=<%= @following[0].avatar_url %> width="50" alt="User Avatar" class="img-circle" />
          </div>

          <div class="mq-friends-footer">
              <small><%= @following[0].username %> </small>
          </div>
      </div>

      <div class="mq-friends thumbnail">
              <div class="mq-friend-img text-center">
              <img src=<%= @following[1].avatar_url %> width="50" alt="User Avatar" class="img-circle" />
          </div>

          <div class="mq-friends-footer">
              <small><%= @following[1].username %> </small>
          </div>
      </div>

      <div class="mq-friends thumbnail">
              <div class="mq-friend-img text-center">
              <img src=<%= @following[2].avatar_url %> width="50" alt="User Avatar" class="img-circle" />
          </div>

          <div class="mq-friends-footer">
              <small><%= @following[2].username %> </small>
          </div>
      </div>

      <div class="mq-friends thumbnail">
              <div class="mq-friend-img text-center">
              <img src=<%= @following[3].avatar_url %> width="50" alt="User Avatar" class="img-circle" />
          </div>

          <div class="mq-friends-footer">
              <small><%= @following[3].username %> </small>
          </div>
      </div>

      <div class="mq-friends thumbnail">
              <div class="mq-friend-img text-center">
              <img src=<%= @following[4].avatar_url %> width="50" alt="User Avatar" class="img-circle" />
          </div>

          <div class="mq-friends-footer">
              <small><%= @following[4].username %> </small>
          </div>
      </div>

      <div class="mq-friends thumbnail">
              <div class="mq-friend-img text-center">
              <img src=<%= @following[5].avatar_url %> width="50" alt="User Avatar" class="img-circle" />
          </div>

          <div class="mq-friends-footer">
              <small><%= @following[5].username %> </small>
          </div>
      </div>

    </div>
  </div>
</div>

<div class="mq-panel-wrapper">
  <div class="mq-panel-header">
      <h3>Pull Requests</h3>
  </div>

  <div class="mq-panel-body">
    <% @prs.each do |requests| %>
       <ul class="mq-comment">
          <div class="mq-comment-body clearfix">
              <div class="header">
                  <p><strong class="primary-font">Pull Request User: <%= requests['user']['login'] %></strong></p>
                  <p><strong class="primary-font">Message: <%= requests['body'] %></strong></p>
                  <small class="pull-right text-muted">
                    <span class="glyphicon glyphicon-time"></span>
                   </small>
              </div>
          </div>
        </ul>
    <% end %>
  </div>
</div>

<div class="mq-panel-wrapper">
  <div class="mq-panel-header">
      <h3>Friends Recent Activity</h3>
  </div>

  <div class="mq-panel-body">
    <% @all_events.each do |event| %>
       <ul class="mq-comment">
                  <div class="mq-comment-body clearfix">
                      <div class="header">
                          <strong class="primary-font"><%= event.first['type'] %></strong> <small class="pull-right text-muted">
                              <span class="glyphicon glyphicon-time"></span><%= distance_of_time_in_words Time.now, event.first['created_at'] %></small>
                      </div>
                      <p>
                        <%= event.first['body'] %>
                      </p>
                  </div>
          </ul>
        <% end %>
  </div>
</div>

<div class="mq-panel-wrapper">
  <div class="mq-panel-header">
      <h3>My Repositories</h3>
      <p><a href="/"></a></p>
  </div>

  <div class="mq-panel-body">
    <% @repos.each do |repo| %>
       <ul class="mq-comment">
          <div class="mq-comment-body clearfix">
              <div class="header">
                  <strong class="primary-font">Name: <%= repo.repo_name %></strong>
                  <strong class="primary-font">Owner: <%= repo.owner_name %></strong>
                  <small class="pull-right text-muted">
                    <span class="glyphicon glyphicon-time"></span>
                   </small>
              </div>
          </div>
        </ul>
    <% end %>
  </div>
</div>

<div class="mq-panel-wrapper">
  <div class="mq-panel-header">
      <h3>Recent Commits</h3>
  </div>

  <div class="mq-panel-body">
    <% @commits.each do |commit| %>
       <ul class="mq-comment">
          <div class="mq-comment-body clearfix">
              <div class="header">
                  <p><strong class="primary-font">Date Created: <%= commit.created_at %></strong></p>
                  <p><strong class="primary-font">Message: <%= commit.message %></strong></p>
                  <small class="pull-right text-muted">
                    <span class="glyphicon glyphicon-time"></span>
                   </small>
              </div>
          </div>
        </ul>
    <% end %>
  </div>
</div>

<div class="mq-panel-wrapper">
  <div class="mq-panel-header">
      <h3>Organizations</h3>
  </div>

  <div class="mq-panel-body">
    <% unless @organizations.nil? %>
      <% @organizations.each do |org| %>
       <ul class="mq-comment">
        <div class="mq-comment-body clearfix">
          <div class="header">
            <strong class="primary-font"><%= org['name'] %></strong> <small class="pull-right text-muted">
          </div>
         </div>
       </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="panel panel-default">
	  	<div class="panel-heading">
	    	<h3 class="panel-title">Welcome To GITs Mini Bro</h3>
	 	  </div>
    <% if current_user %>
      Hello, <%= current_user.name %>.
      <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
	  	<div class="panel-body">
        <!-- <%= form_for :session, url: login_path  do |f|  %>
                <fieldset>
                  <div class="form-group">
                    <%= f.label :email, class: "form-control" %>
                    <div class="cols-sm-10">
                      <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                        <%= f.text_field :email, class: "form-control", placeholder: "Enter Email" %>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :password, class: "form-control" %>
                    <div class="cols-sm-10">
                      <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                        <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
                      </div>
                    </div>
                  </div> -->
                  <div class="form-group ">
            				<!-- <%= f.submit "Log On", id: "button", class: "btn btn-success btn-lg btn-block login-button" %> -->
                    <%= button_to "Create Account with Github", github_login_path, class: "btn btn-primary btn-md btn-block login-button" %>
            			</div>
          <% end %>
	    	</fieldset>
                  <hr/>
                <center><h4>OR</h4></center>
          <%= button_to "Sign in with GitHub", github_login_path, class: "btn btn-lg btn-github btn-block" %>
	    </div>
      <% end %>
	</div>
</div>
</div>

app/views/layouts/_errors.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, raw(msg), class: "alert alert-#{name} text-center"  %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Gits Mini Bro</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><a href="#"> <%= "Logged in as #{current_user_name}" %> </a></li>
          <li> <%= link_to "Logout", login_path, method: :delete %></li>
        <% else %>
          <li><a href="/auth/github">Signup</a></li>
          <li><a href="/auth/github">Login</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GhubMiniBro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/errors' %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user/dashboard/index.html.erb
<h1>User::Dashboard#index</h1>
<p>Find me in app/views/user/dashboard/index.html.erb</p>

app/views/user/dashboard/show.html.erb
<h1>User::Dashboard#show</h1>
<p>Find me in app/views/user/dashboard/show.html.erb</p>